project_id = "nzbvcrbmauriwtjndkpt"

[functions.send-email]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true

[functions.create-agency-user]
verify_jwt = true

[functions.delete-agency-user]
verify_jwt = true

[functions.update-user-password]
verify_jwt = true

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.manage-subscription]
verify_jwt = true
